###################### USERS ############################
### Users Index
GET http://localhost:3000/users.json

### Users Show
GET http://localhost:3000/users/2.json

### Users Create
POST http://localhost:3000/users.json
Content-Type: application/json

{
  "name": "test name",
  "email": "test@example.com",
  "password": "password",
  "council": "defense"
}
### Users Destroy
DELETE http://localhost:3000/users/3.json

### Users Update
PATCH http://localhost:3000/users/4.json
Content-Type: application/json

{ "council": "defense" }

############################# JURORS ########################
### Jurors Index
GET http://localhost:3000/jurors.json

### Jurors Show
GET http://localhost:3000/jurors/1.json

### Jurors Update
PATCH http://localhost:3000/jurors/21.json
Content-Type: application/json

{
  "jury_pool": false,
  "jury_box": true,
}

### Jurors Destroy
DELETE http://localhost:3000/jurors/21.json

### Jurors Create
POST http://localhost:3000/jurors.json
Content-Type: application/json

{
  "panel_number": 21,
  "name": "test name",
  "age": 45,
  "sex": "male",
  "residence": "test residence",
  "housing": "test housing",
  "education": "test eduction",
  "law_experience": "none",
  "occupation": "test occupation",
  "military_experience": "none",
  "jury_relation": "none",
  "prior_jury": "none",
  "notes": "notes test",
  "jury_pool": true,
  "jury_box": false,
  "jury_alternative": false
}